[package]
name = "sample-rust-project"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0"
tokio = { version = "1.0", features = ["full"] }
reqwest = "0.11"
clap = "4.0"

[dev-dependencies]
tokio-test = "0.4"
